dispatcher/urls.py
from django.conf.urls import patterns, url

from dispatcher import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^lend/$', views.lend, name='lend'),
    url(r'^userdetail/$', views.userdetail, name='userdetail'),
    url(r'^machinedetail/$', views.machinedetail, name='machinedetail'),
)

machines/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'machines.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^dispatcher/', include('dispatcher.urls', namespace='dispatcher')),
    url(r'^admin/', include(admin.site.urls)),
)

dispatcher/models.py
from django.db import models

# Create your models here.


class Owner(models.Model):
    name    = models.CharField(max_length=20)
    email   = models.EmailField(max_length=70)
    passwd  = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name

class Machine(models.Model):
    hostname = models.CharField(max_length=40)
    dtlref   = models.CharField(max_length=100, blank=True, null=True)
    arch     = models.CharField(max_length=20)
    os       = models.CharField(max_length=20)
    location = models.CharField(max_length=20)
    status   = models.CharField(max_length=10)
    note     = models.TextField(blank=True, null=True)
    owner  = models.ForeignKey(Owner)

    def __unicode__(self):
        return self.hostname

dispatcher/views.py
from django.shortcuts import render

from dispatcher.models import Machine, Owner
from django.http import HttpResponse

# Create your views here.
def index(request):
    machine_list = Machine.objects.all()
    return render(request, 'dispatcher/index.html', {'machine_list': machine_list})

def signin(request):
    return render(request, 'dispatcher/signin.html', {})

def login(request):
    usermail = request.POST['loginEmail']
    password = request.POST['loginPasswd']

    try:
        user = Owner.objects.get(email=usermail, passwd=password)
    except Owner.DoesNotExist:
        return HttpResponse("User Not Exist!")
    # return HttpResponse("Login Success!")
    machine_list = Machine.objects.all()
    return render(request, 'dispatcher/logedin.html', {'user': user, 'machine_list': machine_list,})

def signup(request):
    return render(request, 'dispatcher/signup.html', {})

def register(request):
    username = request.POST['userName']
    usermail = request.POST['userEmail']
    password = request.POST['userPasswd']

    user = Owner(name=username, email=usermail, passwd=password)
    user.save()
    return render(request, 'dispatcher/signedup.html', {})


def lend(request):
    user_list = Owner.objects.all()
    return render(request, 'dispatcher/lendto.html', {'user_list': user_list,})


def userdetail(request, username):
    user = Owner.objects.filter(name=username)
    return render(request, 'dispatcher/userdetail.html', {'user': user})

def machinedetail(request, user, machine):
    return render(request, 'dispatcher/machinedetail.html', {'user': user, 'machine': machine})

dispatcher/templates/dispatcher/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HCTS Team Machine Board</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap.min.css' %}">
    <style type="text/css">
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="{% url 'dispatcher:signin' %}"><small>SignIn</small></a></li>
          <li><a href="{% url 'dispatcher:signup' %}"><small>SignUp</small></a></li>
        </ul>
        <h3 class="text-muted">HCTS Team Machine Board</h3>
      </div>
      <br />

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Machine</th>
            <th>Arch</th>
            <th>OS</th>
            <th>Location</th>
            <th>Status</th>
            <th>Owner</th>
            <th>Note</th>
          </tr>
        </thead>
        <tbody>
        {% for machine in machine_list %}
          <tr>
            <td><a href="{{ machine.detail }}">{{ machine.hostname }}</a></td>
            <td>{{ machine.arch }}</td>
            <td>{{ machine.os }}</td>
            <td>{{ machine.location }}</td>
            <td>{{ machine.status }}</td>
            <td>{{ machine.owner }}</td>
            <td>{{ machine.note }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
     
      <div class="footer">
        <p>&copy; HCTS Team 2014 <span>Contact us: </span><span><a href="mailto:nick_chiu@163.com">Email</a></span></p>
      </div>
    </div><!-- container -->
  </body>
</html>

dispatcher/templates/dispatcher/lendto.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap.min.css' %}">
    <style type="text/css">
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="#">{{ user.name }}</a></li>
          <li><a href="#">logout</a></li>
        </ul>
        <h3 class="text-muted">HCTS Team Machine Board</h3>
      </div>
      <div class="row" style="height: 50px">
      </div>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <form class="form-horizontal" role="form" action="{% url 'dispatcher:login' %}" method="post">
          {% csrf_token %}
            <div class="form-group">
              <div class="row">
                <select name="hostname" class="form-control" id="hostname">
                  <option selected>{{ machine.hostname }}
                </select>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <input name="arch" class="form-control" id="arch" value="{{ machine.arch }}" />
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <input name="os" class="form-control" id="os" value="{{ machine.os }}" />
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <input name="os" class="form-control" id="os" value="{{ machine.os }}" />
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <select name="recver" class="form-control" id="recver">
                  {% for recver in user_list %}
                  <option>{{ recver.name }}
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <button type="submit" class="btn btn-primary">Commit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div><!-- container -->
  </body>
</html>

dispatcher/templates/dispatcher/logedin.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HCTS Team Machine Board</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap.min.css' %}">
    <style type="text/css">
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="#">{{ user.name }}</a></li>
          <li><a href="#">logout</a></li>
        </ul>
        <h3 class="text-muted">HCTS Team Machine Board</h3>
      </div>
      <br />

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Machine</th>
            <th>Arch</th>
            <th>OS</th>
            <th>Location</th>
            <th>Status</th>
            <th>Owner</th>
            <th>Note</th>
            <th>Opt</th>
          </tr>
        </thead>
        <tbody>
        {% for machine in machine_list %}
          <tr>
            <td><a href="#">{{ machine.hostname }}</a></td>
            <td>{{ machine.arch }}</td>
            <td>{{ machine.os }}</td>
            <td>{{ machine.location }}</td>
            <td>{{ machine.status }}</td>
            <td>{{ machine.owner }}</td>
            <td>{{ machine.note }}</td>
            {% ifequal machine.owner user %}
<!--            <td><input type="button" value="LENDTO" /></td>   -->
            <td><a href="{% url 'dispatcher:lend' %}">LendTo</a></td>
            {% else %}
<!--            <td><input type="button" value="Mailto" /></td>  -->
            <td><a href="mailto:{{ user.email }}">Mailto</a></td>
            {% endifequal %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
     
      <div class="footer">
        <p>&copy; HCTS Team 2014 <span>Contact us: </span><span><a href="mailto:nick_chiu@163.com">Email</a></span></p>
      </div>
    </div><!-- container -->
  </body>
</html>

dispatcher/templates/dispatcher/signedup.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap.min.css' %}">
    <style type="text/css">
    </style>
  </head>
  <body>
    <h3>Sign up Success!</h3>
    <p>the page is going to jump to the <a href="{% url 'dispatcher:index' %}">home</a> page</p>
    <p>or you can <a href="{% url 'dispatcher:signin' %}">log in</a> here.</p>
    <form name="jumpform" action="{% url 'dispatcher:index' %}" method="get"></form>
    <script>
      setTimeout(function(){document.jumpform.submit();}, 3000);
<!--      document.jumpform.submit(); -->
    </script>
  </body>
</html>

dispatcher/templates/dispatcher/signin.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap.min.css' %}">
    <style type="text/css">
    </style>
  </head>
  <body>
    <div class="container">
      <div class="row" style="height: 50px">
      </div>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <form class="form-horizontal" role="form" action="{% url 'dispatcher:login' %}" method="post">
          {% csrf_token %}
            <div class="form-group">
              <div class="row">
                <input type="email" name="loginEmail" class="form-control" id="loginEmail" placeholder="Email">
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <input type="password" name="loginPasswd" class="form-control" id="loginPassword" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-6">
                  <div class="checkbox">
          	  <label>
          	    <input type="checkbox"> Remember me
          	  </label>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary pull-right">Sign in</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <p>
                <span><small>Don't have an Account?</small></span>
                <span><a href="{% url 'dispatcher:signup' %}"><small>Sign up</small></a></span>
              </p>
            </div>
          </form>
        </div>
      </div>
    </div><!-- container -->
  </body>
</html>

dispatcher/templates/dispatcher/signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap.min.css' %}">
    <style type="text/css">
    </style>
  </head>
  <body>
    <div class="container">
      <div class="row" style="height: 50px">
      </div>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <form class="form-horizontal" role="form" action="{% url 'dispatcher:register' %}" method="post">
          {% csrf_token %}
            <div class="form-group">
              <div class="row">
                <input type="text" name="userName" class="form-control" id="userName" placeholder="Name">
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <input type="email" name="userEmail" class="form-control" id="userEmail" placeholder="Email">
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <input type="password" name="userPasswd" class="form-control" id="userPassword" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-6">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary pull-right">Sign up</button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div><!-- container -->
  </body>
</html>

dispatcher/templates/dispatcher/userdetail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dispatcher/bootstrap.min.css' %}">
    <style type="text/css">
    </style>
  </head>
  <body>
    <h2>{{ user.name }}</h2>now owns the following machine(s):
    <a href="mailto:{{ user.email }}">Mail to me</a>
    <table class="table">
      <thead>
        <tr>
          <th>Machine</th>
          <th>Arch</th>
          <th>OS</th>
          <th>Location</th>
          <th>Status</th>
          <th>Owner</th>
          <th>Note</th>
          <th>LendTo</th>
        </tr>
      </thead>
      <tbody>
      {% for machine in user.machine_set.all() %}
        <tr>
          <td><a href="{{ machine.detail }}">{{ machine.hostname }}</a></td>
          <td>{{ machine.arch }}</td>
          <td>{{ machine.os }}</td>
          <td>{{ machine.location }}</td>
          <td>{{ machine.status }}</td>
          <td>{{ machine.owner }}</td>
          <td>{{ machine.note }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </body>
</html>